[package]
name = "advent_of_code_2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
modpow = "1.0.1"
num-bigint = "0.4.3"
num-integer = "0.1.45"
num-traits = "0.2.15"
regex = "1.7.0"
